# Whisper node parameters
/whisper/whisper_node:
  ros__parameters:
    # Model
    sampling_strategy: "beam_search"
    model_repo: "ggerganov/whisper.cpp"
    model_filename: "ggml-large-v3-turbo-q5_0.bin"
    model_path: ""
    openvino_encode_device: "CPU"

    # Inference
    n_threads: 4
    n_max_text_ctx: 16384
    offset_ms: 0
    duration_ms: 0
    translate: false
    no_context: true
    single_segment: false

    # Token timestamps
    token_timestamps: false
    thold_pt: 0.01
    thold_ptsum: 0.01
    max_len: 0
    split_on_word: false
    max_tokens: 0
    audio_ctx: 0
    suppress_regex: ""

    # Language
    language: "en"
    detect_language: false

    # Decoding
    suppress_blank: true
    suppress_nst: false
    temperature: 0.0
    max_initial_ts: 1.0
    length_penalty: -1.0
    temperature_inc: 0.2
    entropy_thold: 2.4
    logprob_thold: -1.0
    no_speech_thold: 0.6

    # Sampling strategies
    greedy_best_of: 5
    beam_search_beam_size: 5
    beam_search_patience: -1.0

    # Processing
    n_processors: 1
    flash_attn: true
    use_gpu: true
    gpu_device: 0

    # DTW
    dtw_n_top: -1
    dtw_token_timestamps: false
    dtw_aheads: "none"
